// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohqzudczludypnckqgzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ocXp1ZGN6bHVkeXBuY2txZ3prIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4OTk1NDgsImV4cCI6MjA2ODQ3NTU0OH0.SQiwxiitHEKDJmvCnsLpCe52BsCePz_wPt-xkgbtc-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});